### PR TITLE
Fix failed to run e2e-test on go1.13

### LINKED ISSUE #88: Error when running e2e test
**What happened**:

```
flag provided but not defined: -test.timeout
```

I'm using go1.13. Probably related to https://github.com/golang/go/issues/31859

**How to reproduce it**:

Run `make e2e-test` using go1.13

### PR DESCRIPTION
**Pull request by prksu**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test

/kind failing-test

> /kind feature
> /kind flake

**What this PR does / why we need it**:

Fix failed to run e2e-test on go1.13

Instead of calling `framework.HandleFlags()` in `init()` function, I move it to `ginkgo.BeforeSuite`.
And adding installing and uninstalling driver in suite test like `azuredisk-csi-driver` do.

**Which issue(s) this PR fixes**:

Fixes #88

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by prksu** [comment]
@andyzhangx the failed test, seems because we already have `path_alias` in prow jobs config.

**Comment by prksu** [comment]
I'll wait until this PR #90 merged and rebasing this PR.

**Comment by andyzhangx** [comment]
there is still error like this:
```
2020/01/08 02:35:18 process.go:153: Running: make e2e-test
test/e2e/run-test.sh
E0108 02:36:49.395091   80076 azure.go:47] Failed to load config from file: /etc/kubernetes/azure.json
F0108 02:36:49.396607   80076 blobfuse.go:78] failed to get Azure Cloud Provider
goroutine 28 [running]:
sigs.k8s.io/blobfuse-csi-driver/vendor/k8s.io/klog.stacks(0xc000800200, 0xc0000d86e0, 0x51, 0x14f)
	/home/prow/go/src/sigs.k8s.io/blobfuse-csi-driver/vendor/k8s.io/klog/klog.go:855 +0xb8
sigs.k8s.io/blobfuse-csi-driver/vendor/k8s.io/klog.(*loggingT).output(0x30ae9c0, 0xc000000003, 0xc0001c29a0, 0x2f5a8ad, 0xb, 0x4e, 0x0)
	/home/prow/go/src/sigs.k8s.io/blobfuse-csi-driver/vendor/k8s.io/klog/klog.go:806 +0x351
sigs.k8s.io/blobfuse-csi-driver/vendor/k8s.io/klog.(*loggingT).println(0x30ae9c0, 0x3, 0xc0006d1f60, 0x1, 0x1)
	/home/prow/go/src/sigs.k8s.io/blobfuse-csi-driver/vendor/k8s.io/klog/klog.go:683 +0xe7
sigs.k8s.io/blobfuse-csi-driver/vendor/k8s.io/klog.Fatalln(...)
	/home/prow/go/src/sigs.k8s.io/blobfuse-csi-driver/vendor/k8s.io/klog/klog.go:1249
```
@chewong

**Comment by andyzhangx** [comment]
sorry to close this PR since it's not in the correct way, we should depend on helm to run e2e test.

**Pull request closed without merging**
