### PR TITLE
Setup code verification and unit test CI

### PR DESCRIPTION
**Pull request by chewong**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

We will need to manually merge this PR after code verification and unit test CI pass.
/assign @andyzhangx 

**Which issue(s) this PR fixes**:

Related issue: #9

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Comment by chewong** [comment]
pull-blobfuse-csi-driver-unit and pull-blobfuse-csi-driver-verify have passed. I will open another PR to fix sanity, integration and e2e tests CI.

**Comment by andyzhangx** [comment]
wow, thanks
cc @ritazh 
/pony

**Comment by chewong** [comment]
@andyzhangx I've finished setting up sanity and integration test in #86. Could you manually review and merge this PR so #86 can rebase? Thanks.

**Pull request merged**
